name: Build code, run unit test, run SAST, SCA, DAST security scans for NodeJs App
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    name: Run unit tests and SAST scan on the source code 
    steps:
    - uses: actions/checkout@v3
    - run: npm install
    - uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: npm
    - name: Run Semgrep Scan
      uses: returntocorp/semgrep-action@v1
      with:
        config: "p/security-audit"
